name: C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: configure
      run: gcc -o coolbuild coolbuild.c
    - name: build
      run: ./coolbuild
    - name: test
      run: ./coolbuild test
